[env]
HOLODECK_SSL_CERT_PATH = "/Users/jonno/holodeck-localhost.pem"
HOLODECK_SSL_KEY_PATH = "/Users/jonno/holodeck-localhost-key.pem"

[settings]
trusted_config_paths = ["~/src/btp"]

[tools]
"npm:corepack" = "latest"
age = "latest"
bun = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
cloudflared = "latest"
cosign = "latest"
deno = "2"
dotnet = "9"
flux2 = "latest"
go = "latest"
helm = "latest"
jq = "latest"
kubectl = "latest"
node = "24"
opentofu = "latest"
packer = "latest"
python = "latest"
slsa-verifier = "latest"
sops = "latest"
talosctl = "latest"
uv = "latest"

[task_config]
includes = ["tasks/dotfiles.toml"]
